### PR TITLE
Fix build on systems without TCP_NOTSENT_LOWAT.

### PR DESCRIPTION
**Pull request by twasilczyk**
This option is not available on kernels older than 3.12 and may still
not be available on some newer.

### CODE REVIEW

**Comment by Abhayakara** [comment]
This looks good. I will integrate it as soon as I can.

**Comment by Abhayakara** [comment]
FYI I have started an internal pull request on this (and I'll try to do it for the others today as well, if possible). Once these are approved, they'll be committed to our internal repo. The next step is going to be to apply all the changes to the external repo, after which this change will show up. This PR won't actually show as merged, because I have to do it from the other direction, but it will in fact be merged. I'll annotate the PRs that are merged by closing them with a comment when this is done.

**Comment by twasilczyk** [comment]
That's exactly a process I thought you would take. Looking forward to  it happen!

Once I sync on these changes that come back, I'll spin off the next round of patches if necessary.

Thanks!

**Comment by twasilczyk** [comment]
I enumerated all the changes of our fork against the upstream, categorized and prioritized. Please take a look and let me know if you disagree with any that are marked for pushing upstream: [spreadsheet](https://docs.google.com/spreadsheets/d/15RiF4rrKk4C9eAk7rAQxUY5MnkVJeNKwXLtSkuEsANo/edit). If you don't have gmail account, I can generate a PDF or xls for you.

Once we get aligned on the point of these changes, I'll start preparing pull requests. For some of these the PR would have to be vastly different (i.e. how it's hacked in Android vs how it should be implemented in upstream), so please evaluate the problems only and not the code.

**Comment by Abhayakara** [comment]
Okay, I've added comments to all of the proposals. I'm assuming you want to wait on this until I push the new code? That would be what I'd recommend—I think I made quite a few changes to the posix code that aren't yet reflected in the github repo.

Ideally it would be good to do these as patches. It looks like extracting them from the Android repo myself would be challenging.

**Comment by twasilczyk** [comment]
Thanks, I've seen them and I'll work on the PRs after you push the new code. It may take over a month because after next week I'm going on month+ leave, but I hope we won't loose momentum after I get back :).

I agree with the latter sentence - justifying some of these changes would require looking through our internal bug tracker or reaching out directly to the authors. It is challenging for me too, but I'm trying to untangle our mess methodically.

**Comment by Abhayakara** [comment]
Sounds good. That's a good time frame for me anyway. Have a good leave!

**Comment by Abhayakara** [comment]
This pull request has been merged to the internal repo and was included in the mDNSResponder-1587 commit.

**Pull request closed without merging**
